config/routes.rb
Rails.application.routes.draw do

  root to: 'home#welcome'
  get 'home/welcome'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/users/:id/credentials/edit', to: 'users#edit_credentials', as: 'edit_credentials'
  put '/users/:id/credentials', to: 'user#update_credentials'
  patch '/users/:id/credentials', to: 'user#update_credentials'
  resources :users
  resources :meals
  resources :logs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
    belongs_to :user
    has_many :log_meals
    has_many :meals, through: :log_meals
    validates :date, presence: true
    validates :date, date: true
    validates :date, 
            date: { before_or_equal_to: Proc.new {Time.now} }
    accepts_nested_attributes_for :meals

    def meals_attributes=(meal_attributes)
        meal_attributes.values.each do |meal_attribute|
            if meal_attribute["meal_name"].present?
                meal = Meal.find_or_create_by(meal_attribute)
                self.meals << meal
            end
        end
    end
    

end

app/models/log_meal.rb
class LogMeal < ApplicationRecord
    belongs_to :log
    belongs_to :meal


end

app/models/logmeal.rb
class LogMeal < ApplicationRecord
    belongs_to :log
    belongs_to :meal


end

app/models/meal.rb
class Meal < ApplicationRecord
    has_many :log_meals
    has_many :logs, through: :log_meals
    validates :meal_type, presence: true
    validates :meal_name, presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
  has_many :logs
  has_secure_password
  validates :email, uniqueness: true
  validates :email, presence: true
  validates :email, confirmation: true
  validates :username, uniqueness: true
  validates :username, presence: true
  

  def self.create_from_omniauth(auth)
    User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
        u.username = auth['info']['first_name']
        u.email = auth['info']['email']
        u.password = SecureRandom.hex(16)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include ApplicationHelper

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
    before_action :logged_in?, only: [:new, :index, :show, :edit, :update]
    before_action :find_log, only: [:show, :edit, :update, :destroy]

    

    def index
        @logs = @current_user.logs
    end

    def new
        @log = Log.new
       
      
    end

    def create
        @log = Log.new(log_params)
        if @log.save
            redirect_to log_path(@log)
        else
            render :new
            
        end
    end

    def show
        @log
    end

    def edit
        @log
    end

    def update
        if @log.update(log_params)
            redirect_to log_path(@log)
        else
            render :edit
        end
    end

    def destroy
        @log.destroy
        redirect_to logs_path
    end
    
    private

    def log_params
        params.require(:log).permit(:date, :cheat_day, :cal_goal, :protein_goal, :carb_goal, :fat_goal, :water_goal, :sugar_goal, :cal_goal, :protein_count, :carb_count, :fat_count, :water_count, :sugar_count, meal_ids: [], meals_attributes:[:meal_type, :meal_name, :cal_amount, :protein_amount, :carb_amount, :fat_amount, :water_amount, :sugar_amount, :cheat_meal, :meal_id])
    end

    def find_log
        @log = Log.find(params[id])
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
    before_action :logged_in?, only: [:index, :show, :edit, :update]
    before_action :find_meal, only: [:show, :edit, :update, :destroy]
    

    def index
        @meals = @current_user.logs.meals.unique
    end

    def new
        @meal = Meal.new
    end

    def create
        @meal = Meal.new(meal_params)
        if @meal.save
            redirect_to meal_path(@meal)
        else
            render :new
            flash[:message] = @meal.errors.full_messages.join(", ")
        end
    end

    def show
        @meal
    end

    def edit
        @meal
    end

    def update
        if @meal.update(meal_params)
            redirect_to meal_path(@meal)
        else
            render :edit
        end
    end

    def destroy
        @meal.destroy
        redirect_to meals_path
    end
    
    private

    def meal_params
        params.require(:meal).permit(:meal_type, :meal_name, :cal_amount, :protein_amount, :carb_amount, :fat_amount, :water_amount, :sugar_amount, :cheat_meal)
    end

    def find_meal
        @meal = Meal.find(params[id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        if logged_in?
            redirect_to user_path
        end
    end

    def create
        user = User.find_by(params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            flash[:message] = "Invalid credentials. Please try again."
            redirect_to '/login', alert: "Invalid credentials. Plase try again."
        end
    end

    def omniauth
        user = User.create_from_omniauth(auth)
        if user.valid?
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            flash[:message] = user.errors.full_messages.join(", ")
            redirect_to new_user_path
        end
    end


    def destroy
        session.delete(:user_id)
        redirect_to root_path
    end

    private

    def auth
        request.env['omniauth.auth']
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in?, :redirect_if_not_logged_in, only: [:show, :edit, :update, :edit_credentials, :update_credentials]

    def new
        if !logged_in?
            @user = User.new
        else
            flash[:message] = "You are already logged in."
            redirect_to user_path(@current_user)
        end

    end

    def create
        user = User.new(user_params)
        if user.save
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            render :new
        end
    end

    def show
    end

    def edit
        
    end

    def update
        if @current_user.update(profile_update_params)
            redirect_to user_path(@current_user)
        else
            render :edit
        end
    end

    def edit_credentials
        
    end

    def update_credentials
        if @current_user.update(credentials_update_params)
            redirect_to user_path(@current_user)
        else
            render :edit
        end
    end



    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :first_name, :last_name, :bio, :weight, :height, :goal, :lifestyle)
    end

    def profile_update_params
        params.require(:user).permit(:first_name, :last_name, :bio, :weight, :height, :goal, :lifestyle)
    end

    def credentials_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def redirect_if_not_logged_in
        if !logged_in?
            redirect_to root_path
        end
    end


    
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper

end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nutricount</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
  
    <%= yield %>
  </body>
</html>

app/views/logs/_log_form.html.erb
<%= form_with model: @log do |f| %>
    <% if @log.errors.any? %>
    <ul>
    <% @log.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
    <%= f.label :date %> <br>
    <%= f.date_field :date %> <br>
    <%= f.label :cheat_day %> <br>
    <%= f.check_box :cheat_day %> <br>
    <%= f.label :cal_goal %> <br>
    <%= f.number_field :cal_goal, step: 1.0 %> <br>
    <%= f.label :protein_goal %> <br>
    <%= f.number_field :protein_goal, step: 1.0 %> <br>
    <%= f.label :carb_goal %> <br>
    <%= f.number_field :carb_goal, step: 1.0 %> <br>
    <%= f.label :fat_goal %> <br>
    <%= f.number_field :fat_goal, step: 1.0 %> <br>
    <%= f.label :water_goal %> <br>
    <%= f.number_field :water_goal, step: 1.0 %> <br>
    <%= f.label :sugar_goal %> <br>
    <%= f.number_field :sugar_goal, step: 1.0 %> <br>
    <br>
    <br>
    <p> Select Previously Submitted Meal<br>
    <%= f.label :meal_id, "By Name:" %>
    <%= f.collection_select :meal_id, Meal.all, :id, :meal_name, prompt: true%>
    <p>
    Or Add New Meal:<br>
    <%= f.fields_for :meals, @log.meals.build do |meal_form| %>
        <li>
        <%= meal_form.label :meal_type %> <br>
        <%= meal_form.select :meal_type, ["Breakfast", "Lunch", "Dinner", "Snack", "Misc" ]  %> <br>
        <%= meal_form.label :meal_name %> <br>
        <%= meal_form.text_field :meal_name %> <br>
        <%= meal_form.label :cal_amount %> <br>
        <%= meal_form.text_field :cal_amount %> <br>
        <%= meal_form.label :protein_amount %> <br>
        <%= meal_form.text_field :protein_amount %> <br>
        <%= meal_form.label :carb_amount %> <br>
        <%= meal_form.text_field :carb_amount %> <br>
        <%= meal_form.label :fat_amount %> <br>
        <%= meal_form.text_field :fat_amount %> <br>
        <%= meal_form.label :water_amount %> <br>
        <%= meal_form.text_field :water_amount %> <br>
        <%= meal_form.label :sugar_amount %> <br>
        <%= meal_form.text_field :sugar_amount %> <br>
        <%= meal_form.label :cheat_meal %> <br>
        <%= meal_form.check_box :cheat_meal %> <br>
        </li>
        <%= meal_form.submit 'Add Meal' %> <br>
    <% end %>


    <%= f.submit 'Create Log' %>
<% end %>

app/views/logs/edit.html.erb
<h1> Edit Log/Meals: </h1>

<%= render 'log_form' %>

app/views/logs/index.html.erb
<h3>Your Logs: </h3>

<p>
<% @logs.each do |l| %>
    <%= link_to "#{l.date}", log_path(l) %> <br>
<% end %>


    

app/views/logs/new.html.erb
<h1>Create Meal Log</h1>

<%= render 'log_form' %>

app/views/logs/show.html.erb
<h1> Log For: <%= @log.date %>  </h1>

<%= render log_meal_index %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">NutriCount</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'Profile', user_path(@current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logs', logs_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign Out', logout_path(@current_user), method: :delete, class: 'nav-link' %>
        </li>
        <% else %>
            <li class="nav-item">
            <%= link_to 'Register', new_user_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'Sign In', login_path, class: 'nav-link' %>
            </li>
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<h1> Edit Profile: </h1>

<body>

<%= form_with model: @current_user do |f| %>
    <%= f.label :first_name %> <br>
    <%= f.text_field :first_name %> <br>
    <%= f.label :last_name %> <br>
    <%= f.text_field :last_name %> <br>
    <%= f.label :bio %> <br>
    <%= f.text_area :bio, size: "70x6" %> <br>
    <%= f.label :weight %> <br>
    <%= f.number_field :weight %> <br>
    <%= f.label :height %> <br>
    <%= f.number_field :height %> <br>
    <%= f.label :goal %> <br>
    <%= f.select :goal, ["Weight Loss", "Weight Gain", "Build Muscle"] %> <br>
    <%= f.label :lifestyle %> <br>
    <%= f.select :lifestyle, ["Not Active", "Somewhat Active", "Active", "Very Active"] %> <br>
    <%= f.submit 'Update Profile' %>
    
<% end %>
</body>

app/views/users/edit_credentials.html.erb
<h1> Change Credentials: </h1>

<body>

<%= form_with model: @current_user do |f| %>
    <%= f.label :email %> <br>
    <%= f.email_field :email %> <br>
    <%= f.label :email_confirmation %> <br>
    <%= f.email_field :email_confirmation %> <br>
    <%= f.label :username %> <br>
    <%= f.text_field :username %> <br>
    <%= f.label :password %> <br>
    <%= f.password_field :password %> <br>
    <%= f.label :password_confirmation %> <br>
    <%= f.password_field :password_confirmation %> <br>

    <%= f.submit 'Update Credentials' %>
    
<% end %>
</body>

app/views/users/new.html.erb
<h1> Sign Up Here: </h1>

<body>

<%= form_with model: @user do |f| %>
    <%= f.label :email %> <br>
    <%= f.email_field :email %> <br>
    <%= f.label :email_confirmation %> <br>
    <%= f.email_field :email_confirmation %> <br>
    <%= f.label :username %> <br>
    <%= f.text_field :username %> <br>
    <%= f.label :password %> <br>
    <%= f.password_field :password %> <br>
    <%= f.label :password_confirmation %> <br>
    <%= f.password_field :password_confirmation %> <br>
    <%= f.label :first_name %> <br>
    <%= f.text_field :first_name %> <br>
    <%= f.label :last_name %> <br>
    <%= f.text_field :last_name %> <br>
    <%= f.label :bio %> <br>
    <%= f.text_area :bio, size: "70x6" %> <br>
    <%= f.label :weight %> <br>
    <%= f.number_field :weight %> <br>
    <%= f.label :height %> <br>
    <%= f.number_field :height %> <br>
    <%= f.label :goal %> <br>
    <%= f.select :goal, ["Weight Loss", "Weight Gain", "Build Muscle"] %> <br>
    <%= f.label :lifestyle %> <br>
    <%= f.select :lifestyle, ["Not Active", "Somewhat Active", "Active", "Very Active"] %> <br>
    <%= f.submit 'Sign Up' %>
    
<% end %>

<%= button_to "Log in with Google", '/auth/google_oauth2'  %>

</body>

    
    

app/views/users/show.html.erb
<h2>Your Profile</h2>

<body>
Username: <%= @current_user.username %> <br>
Name: <%= @current_user.last_name %>, <%= @current_user.first_name %> <br>
Height: <%= @current_user.height %> <br>
Weight: <%= @current_user.weight %> <br>
Lifestyle: <%= @current_user.lifestyle %> <br>
Lifestyle: <%= @current_user.goal %> <br>
Bio: <%= @current_user.bio %> <br>
<p>
<%= link_to "Edit Profile", edit_user_path(@current_user) %>
<%= link_to "Update Username/Password", edit_credentials_path(@current_user) %>
</p>
</body>